article/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^blog/$', views.archive, name='archive'),
    url(r'^about/$', views.about, name='about'),
    url(r'^category/(?P<name>\w+)/$', views.category, name='category'),
    url(r'^search/$', views.search, name = 'search'),
    url(r'^(?P<year>[0-9]{4})/$', views.year_archive, name='year_archive'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>0[1-9]|1[0-2])/$', views.month_archive, name='month_archive'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>0[1-9]|1[0-2])/(?P<day>[0-3][0-9])/$', views.day_archive, name='day_archive'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>0[1-9]|1[0-2])/(?P<day>[0-3][0-9])/(?P<title>[\S ]+)/$', views.detail, name='detail'),
] 

blog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('article.urls', namespace='article')),
)

article/models.py
from django.db import models
from django.core.urlresolvers import reverse

from markdown import markdown
# Create your models here.

class Article(models.Model) :
    title = models.CharField(max_length = 100)  
    category = models.CharField(max_length = 50, blank = True)  
    pub_date = models.DateTimeField(auto_now_add = True)  
    content = models.TextField(blank = True, null = True)  

    def get_absolute_url(self):
        return reverse('article:detail', kwargs={'year': self.pub_date.strftime("%Y"), 
                                                'month': self.pub_date.strftime('%m'), 
                                                'day': self.pub_date.strftime('%d'), 
                                                'title': self.title})
    
#    def save(self):
#      self.html = markdown(self.content, 'native')
#      super(Entry, self).save()

    def __str__(self) :
        return self.title

    class Meta:  
        ordering = ['-pub_date']

article/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Article

def index(request):
    latest_article_list =  Article.objects.order_by('-pub_date')[:3]
    context = {'latest_article_list': latest_article_list}
    return render(request, 'article/index.html', context)

def detail(request, year, month, day, title):
    post = get_object_or_404(Article, title=title)
    return render(request, 'article/detail.html', {'post': post})

def archive(request):
    article_list =  Article.objects.order_by('-pub_date')
    paginator = Paginator(article_list, 5)
    page = request.GET.get('page')

    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.paginator(paginator.num_pages)

    context = {'article_list': articles}
    return render(request, 'article/blog.html', context)

def year_archive(request):
    pass

def month_archive(request):
    pass

def day_archive(request):
    pass

def about(request):
    return render(request, 'article/about.html')

def category(request, name):
    article_list = get_list_or_404(Article, category__iexact = name)
    return render(request, 'article/category.html', {'article_list': article_list})


def search(request):
    keyword =  request.GET.get('keyword', '')
    if not keyword.strip() == '':
        query = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        article_list = Article.objects.filter(query)
        return render(request, 'article/search.html', {'article_list': article_list, 'error': 0 == len(article_list)})

    return redirect('/')

article/templates/article/about.html
{% extends "base.html" %}
{% block content %}
<pre>
__About Me__：  

>这个博客是个人知识管理的工具，希望能够帮助自己进步。  
>IT男一枚,技术控，GNU/Linux爱好者。  

- 喜欢的哲学家: 斯宾诺莎、叔本华、庄子  
- 喜欢的歌手: 曹方、陈绮贞、孟庭苇、许巍、伍佰、苏芮  
- 喜欢的电影: 《海上钢琴师》、《地球上的星星》、《A Little Princess》  
- 喜欢的小说: 《匈牙利舞曲》（余泽民）、《草原》（迟子建）、《不能承受的生命之轻》、《月亮与六便士》、《挪威的森林》  
- 喜欢的音乐：

    - 曹方：《比天空还远》，《信》，《最小的海》
    - 陈绮贞：《华丽的冒险》，《鱼》，《失败者的飞翔》，《旅行的意义》，《那么就要出发了么》，《太多》
    - 元若蓝：《绿袖子》
    - 卡奇社：《日光倾城》
    - 许巍：《蓝莲花》,《执着》，《悠远的天空》，《时光》，《旅行》
    - 牛奶咖啡: 《明天, 你好》
    - 王梓盈: 《错过》
    - 筷子兄弟：《老男孩》
    - bandari: 《the first snowflakes》, 《Snowdreams》, 《New Morning》，《The Foggy Dew》，《Mountain stream》，《Moonglow》
    - 李闰珉：《kiss the rain》
    - 伍佰：《与你到永久》，《突然自我》
    - 周华健：《风雨无阻》
    - 孟庭苇：《往事》，《冬季到台北来看雨》，《风中有朵雨做的云》
    - 老狼：《想把我唱给你听》
    - 小昔米：《童年》
    - 郑智化：《星星点灯》
    - 杨蔓的：《蓝眼泪》
    - 车静子：《其实我很在乎你》
    - 张靓颖：《隐形的翅膀》
    - 赵咏华：《最浪漫的事》
    - 蔡琴：《把悲伤留给自己》
    - 黄雅莉：《蝴蝶泉边》
    - 何璐：《让她降落》
    - 任月丽：《微笑着坚强》
    - 王心凌：《我会好好的》
    - 李翊君：《风中的承诺》
    - 毛宁：《涛声依旧》
    - 李健：《中学时代》，《风花树》
    - 朴树：《生如夏花》
    - 崔健：《一无所有》
    - Kenny G： 《Jasmine Flower》，《Going Home》， 《Forever In Love》,《Auld Lang Syne》
    - Christine Glass：《my love will get you home》
    - 外语音乐：《那颗星》，《会有那么一天》，《Je m'appelle Helene》
    - 其它纯音乐：《琵琶语》，《无悔》


__Contact Me__:

+ __Email__: `<xiamingshi[a]live.com>`  
+ __QQ__: 624427998
</pre>
{% endblock %}

article/templates/article/blog.html
{% extends "base.html" %}
{% load custom_markdown %}
{% block content %}
    {% if article_list %}
        <div class="posts">
            {% for post in article_list %}
            <section class="post">
                <header class="post-header">
                <h2 class="post-title"><a href="/{{post.pub_date | date:'Y/m/d'}}/{{ post.title }}/">{{ post.title }}</a></h2>

                        <p class="post-meta">
                        Date:  <a class="post-author" href="#">{{post.pub_date | date:"Y-m-d"}}</a> <a class="post-category post-category-js" href="{% url 'article:category' name=post.category %}">{{ post.category | title }}</a>
                        </p>
                </header>

                    <div class="post-description">
                        <p>
                            {{ post.content | custom_markdown }}
                        </p>
                    </div>
            </section>
        {% endfor %}

        {% if article_list.object_list and article_list.paginator.num_pages > 1 %}
            <div>
            <ul class='pager'>
                {% if article_list.has_previous %}
                <li><a href='?page={{ article_list.previous_page_number }}'>previous</a><li>
                {% endif %}

                {% if article_list.has_next %}
                <li><a href='?page={{ article_list.next_page_number }}'>next</a><li>
                {% endif %}
            </ul>
        </div>
        {% endif %}

    </div>
    {% endif %}
{% endblock %}

article/templates/article/category.html
{% extends "base.html" %}
{% load custom_markdown %}
{% block content %}
    {% if article_list %}
    <div class="posts">
        {% for post in article_list %}
        <section class="post">
            <header class="post-header">
            <h2 class="post-title"> <a href="{{post.get_absolute_url}}">{{ post.title }}</a></h2>

                <p class="post-meta">
                Date:  <a class="post-author" href="#">{{post.pub_date | date:"Y-m-d"}}</a> <a class="post-category post-category-js" href="{% url 'article:category' name=post.category %}">{{ post.category | title }}</a>
                </p>
            </header>

                <div class="post-description">
                    <p>
                        {{ post.content | custom_markdown }}
                    </p>
                </div>
        </section>
    {% endfor %}
    </div>
    {% endif %}
{% endblock %}

article/templates/article/detail.html
{% extends "base.html" %}
{% load custom_markdown %}
{% block content %}
    <div class="posts">
        <section class="post">
            <header class="post-header">
                <h2 class="post-title">{{ post.title }}</h2>

                    <p class="post-meta">
                    Date:  <a class="post-author" href="#">{{post.pub_date | date:"Y-m-d"}}</a> <a class="post-category post-category-js" href="#">{{ post.category }}</a>
                    </p>
            </header>

                <div class="post-description">
                    <p>
                        {{ post.content | custom_markdown }}
                    </p>
                </div>
        </section>
    </div>
{% endblock %}

article/templates/article/index.html
{% extends "base.html" %}
{% load custom_markdown %}
{% block content %}
    {% if latest_article_list %}
    <div class="posts">
        {% for post in latest_article_list %}
        <section class="post">
            <header class="post-header">
            <h2 class="post-title"> <a href="{{post.get_absolute_url}}">{{ post.title }}</a></h2>

                <p class="post-meta">
                Date:  <a class="post-author" href="#">{{post.pub_date | date:"Y-m-d"}}</a> <a class="post-category post-category-js" href="{% url 'article:category' name=post.category %}">{{ post.category | title }}</a>
                </p>
            </header>

                <div class="post-description">
                    <p>
                        {{ post.content | custom_markdown }}
                    </p>
                </div>
        </section>
    {% endfor %}
    </div>
    {% endif %}
{% endblock %}

article/templates/article/search.html
{% extends "base.html" %}
{% load custom_markdown %}
{% block content %}
    <div class="posts">
    {% if error %}
        <h2 class="post-title">没有相关文章题目</a></h2>
    {% else %}
        {% for post in article_list %}
            <section class="post">
                <header class="post-header">
                <h2 class="post-title"> <a href="{{post.get_absolute_url}}">{{ post.title }}</a></h2>

                    <p class="post-meta">
                    Date:  <a class="post-author" href="#">{{post.pub_date | date:"Y-m-d"}}</a> 
                    <a class="post-category post-category-js" href="{% url 'article:category' name=post.category %}">{{ post.category | title }}</a>
                    </p>
                </header>

                    <div class="post-description">
                        <p>
                            {{ post.content | custom_markdown }}
                        </p>
                    </div>
            </section>
        {% endfor %}
    {% endif %}
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="A layout example that shows off a blog page with a list of posts.">

    <title>知静斋</title>
    <link rel="stylesheet" href="/static/article/native.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
    <link rel="stylesheet" href="http://picturebag.qiniudn.com/blog.css">
</head>
<body>
<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header">
            <h1 class="brand-title"><a href="{% url 'article:index' %}">知静斋</a></h1>
            <!--<h2 class="brand-tagline">雪忆 - Snow Memory</h2>-->
            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        <a class="pure-button" href="https://github.com/Andrew-liu">Github</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="/blog/">archive</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="/about/">About Me</a>
                    </li>
                    <li>
                        <form class="pure-form" action="/search/" method="get">
                        <input class="pure-input-3-3" type="text" name="keyword" placeholder="search">
                        </form>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            {% block content %}
            {% endblock %}
            <div class="footer">
                <div class="pure-menu pure-menu-horizontal pure-menu-open">
                    <ul>
                        <li><a href="/about/">About Me</a></li>
                        <li><a href="http://twitter.com/yuilibrary/">Twitter</a></li>
                        <li><a href="http://github.com/yahoo/pure/">GitHub</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

templates/test.html
<!DOCTYPE html>
<html>
    <head>
        <title>Just test template</title>
        <style>
            body {
               background-color: red;
            }
            em {
                color: LightSeaGreen;
            }
        </style>
    </head>
    <body>
        <h1>Hello World!</h1>
        <strong>{{ current_time }}</strong>
    </body>
</html>